server:
  port: 9527

spring:
  application:
    name: cloud-seckill-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://cloud-seckill-service #匹配后提供服务的路由地址
        predicates:
        - Path=/seckill/**         # 断言，路径相匹配的进行路由


management:
  endpoints:
    web:
      exposure:
        include: '*'